[libdefaults]
dns_lookup_realm = true
ticket_lifetime = 24h
renew_lifetime = 7d
forwardable = true
rdns = false
default_realm = WIN.SLAC.STANFORD.EDU
#default_realm = WIN.IINSIC.COM
udp_preference_limit = 0
