git_protocol: ssh
glamour_style: dark
check_update: true
last_update_check_timestamp: 2026-07-07T12:54:07-07:00
display_hyperlinks: false
host: code.stanford.edu
no_prompt: false
telemetry: true
hosts:
    code.stanford.edu:
        git_protocol: ssh
        container_registry_domains: code.stanford.edu,code.stanford.edu:443,registry.code.stanford.edu
        api_host: code.stanford.edu
        api_protocol: https
        user: swl
last_seen_version: v1.106.0
use_keyring: "true"
