git_protocol: ssh
glamour_style: dark
check_update: true
last_update_check_timestamp: 2026-05-17T22:22:52-07:00
display_hyperlinks: false
host: code.stanford.edu
no_prompt: false
telemetry: true
hosts:
    code.stanford.edu:
        git_protocol: ssh
